---
jobs:

- name: bump-version
  serial_groups: [build]
  plan:
  - in_parallel:
    - get: source
      trigger: true
    - get: infrastructure
  - task: bump-version
    file: infrastructure/pipelines/tasks/bump-version-and-commit.yaml
    params:
      private_key: ((gcs-proxy.repo-key))
  - put: push-bumped-version
    resource: source-put
    params:
      repository: source-modified
      rebase: true

- name: build
  serial_groups: [build]
  disable_manual_trigger: true
  plan:
  - in_parallel:
    - get: release-manifests
    - get: infrastructure
    - get: source
      resource: source-put
      passed: [bump-version]
      trigger: true
  - task: parse-app-and-version
    file: infrastructure/pipelines/tasks/parse-app-and-version.yaml
  - in_parallel:
    - task: kustomize-commit-release-manifests
      file: infrastructure/pipelines/tasks/kustomize-build-commit.yaml
    - do:
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
              tag: "0.1.0"
          inputs:
          - name: source
          outputs:
          - name: image
          run:
            path: build
          caches:
          - path: cache
          params:
            CONTEXT: source
      - put: image
        params:
          image: image/image.tar
          additional_tags: version/version
  - in_parallel:
    - put: source-put
      params:
        repository: source
        tag: version/version
        tag_prefix: v
        only_tag: true
    - put: release-manifests
      params:
        repository: release-manifests-modified
        rebase: true

resources:

- name: source
  type: git
  icon: github-circle
  source:
    &source
    branch: master
    uri: git@github.com:boclips/gcs-proxy.git
    private_key: ((gcs-proxy.repo-key))

- name: source-put
  type: git
  icon: github-circle
  source: *source

- name: release-manifests
  type: git
  icon: github-circle
  source:
    uri: git@github.com:boclips/release-manifests-direct-deploy.git
    branch: master
    private_key: ((release-manifests-direct-deploy.repo-key))

- name: infrastructure
  type: git
  icon: github-circle
  source:
    branch: master
    private_key: ((infrastructure.repo-key))
    uri: git@github.com:boclips/infrastructure.git

- name: image
  type: registry-image
  icon: docker
  source:
    repository: eu.gcr.io/boclips-prod/boclips/gcs-proxy
    username: _json_key
    password: ((image-writer.google-storage-key))
